# Generated by Django 5.1.1 on 2025-07-20 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pdf_processing', '0005_uploadedexcel_processingbatch_excel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='extracted_images/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_images', to='pdf_processing.uploadedpdf')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_result', models.JSONField(blank=True, null=True)),
                ('analysis_successful', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('processed_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='image_processing.processedimage')),
            ],
        ),
    ]
