"""
Django settings for ChannelSynthesizerWeb project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# settings.py

"""
Django settings for ChannelSynthesizerWeb project.
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Charger les variables d'environnement du fichier .env
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# --- CONFIGURATION DES SECRETS ---
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-t+01!urh+6^!^wv9@h(w)*+v^rrl8#9mhvke_@y8vv6*2hsf43"
)
DEBUG = os.getenv("DEBUG", "True") == "True"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# --- APPS ---
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "pdf_processing",
    "reporting",
    "accounts",
    "image_processing",
    "storages",
]

# --- MIDDLEWARE ---
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# --- URLS ET TEMPLATES ---
ROOT_URLCONF = "ChannelSynthesizerWeb.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
WSGI_APPLICATION = "ChannelSynthesizerWeb.wsgi.application"

# --- BASE DE DONNÉES ---
DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True,
    )
}

# --- VALIDATION DE MOT DE PASSE ---
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --- INTERNATIONALISATION ---
LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "Europe/Brussels"
USE_I18N = True
USE_TZ = True

# --- GESTION DES FICHIERS ---

# 1. Fichiers Statiques (CSS, JS)
STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# 2. Fichiers Media (PDFs, etc.) - C'EST ICI QU'IL FAUT METTRE LE IF/ELSE
if "AZURE_ACCOUNT_NAME" in os.environ and not DEBUG:
    # --- CONFIGURATION POUR LA PRODUCTION (AZURE) ---
    print("--- Configuration du stockage de fichiers sur AZURE ---")
    DEFAULT_FILE_STORAGE = "storages.backends.azure_storage.AzureStorage"
    AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME")
    AZURE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY")
    AZURE_CONTAINER = "media"
    MEDIA_URL = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER}/"
else:
    # --- CONFIGURATION POUR LE DÉVELOPPEMENT LOCAL ---
    print("--- Configuration du stockage de fichiers sur le DISQUE LOCAL ---")
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# --- GESTION DE LA CONNEXION ---
LOGIN_REDIRECT_URL = "/upload/"
LOGOUT_REDIRECT_URL = "/login/"
LOGIN_URL = "/login/"

# --- TYPE DE CLÉ PRIMAIRE ---
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
