"""
Django settings for ChannelSynthesizerWeb project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from decouple import config
import dj_database_url

# --> AJOUTEZ CETTE LIGNE POUR LE TEST <--
print(
    f"--- TEST DE DEBUG --- La valeur de DB_NAME lue est : '{config('DB_NAME', default='!!! NON TROUVÉ !!!')}'"
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ==============================================================================
# CONFIGURATION DE SÉCURITÉ ET DE L'ENVIRONNEMENT
# Ces valeurs sont chargées depuis votre fichier .env en local,
# et depuis les "Application Settings" sur Azure.
# ==============================================================================
SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)

# Clés pour les services Azure AI
VISION_ENDPOINT = config("VISION_ENDPOINT", default="")
VISION_KEY = config("VISION_KEY", default="")

# Hôte autorisé. Sur Azure, la variable 'WEBSITE_HOSTNAME' est fournie automatiquement.
ALLOWED_HOSTS = [config("WEBSITE_HOSTNAME", default="127.0.0.1")]


# ==============================================================================
# GESTION DES APPLICATIONS ET DES URLS
# ==============================================================================

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pdf_processing",
    "reporting",
    "accounts",
    "image_processing",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Middleware WhiteNoise pour servir les fichiers statiques en production
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ChannelSynthesizerWeb.urls"
WSGI_APPLICATION = "ChannelSynthesizerWeb.wsgi.application"


# ==============================================================================
# CONFIGURATION DES TEMPLATES
# ==============================================================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ==============================================================================
# CONFIGURATION DE LA BASE DE DONNÉES
# Utilise dj-database-url pour se connecter à la base de données définie
# dans la variable d'environnement DATABASE_URL (sur Azure) ou utilise
# les variables locales (dans .env) par défaut.
# ==============================================================================
DATABASES = {
    "default": dj_database_url.config(
        default=f"postgresql://{config('DB_USER')}:{config('DB_PASSWORD')}@{config('DB_HOST')}:{config('DB_PORT')}/{config('DB_NAME')}"
    )
}


# ==============================================================================
# VALIDATION DES MOTS DE PASSE
# ==============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ==============================================================================
# INTERNATIONALIZATION
# ==============================================================================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ==============================================================================
# FICHIERS STATIQUES (CSS, JS, Images du site)
# WhiteNoise se chargera de servir les fichiers collectés dans STATIC_ROOT.
# ==============================================================================
STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ==============================================================================
# FICHIERS MEDIA (Fichiers uploadés par les utilisateurs)
# ATTENTION : En production sur Azure, le stockage local est temporaire.
# Pour une solution fiable, il faudra configurer Azure Blob Storage ici.
# ==============================================================================
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")


# ==============================================================================
# CONFIGURATION DE L'AUTHENTIFICATION
# ==============================================================================
LOGIN_REDIRECT_URL = "/upload/"
LOGOUT_REDIRECT_URL = "/login/"
LOGIN_URL = "/login/"


# ==============================================================================
# CONFIGURATION DU MODÈLE PAR DÉFAUT
# ==============================================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
