# Generated by Django 5.1.1 on 2024-10-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider_period', models.CharField(max_length=100)),
                ('region_flanders', models.BooleanField()),
                ('brussels', models.BooleanField()),
                ('region_wallonia', models.BooleanField()),
                ('german_community', models.BooleanField()),
                ('basic_option', models.CharField(max_length=10)),
                ('tv_radio', models.CharField(max_length=10)),
                ('hd_sd', models.CharField(max_length=5)),
                ('channel_group_level', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('provider', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
