# Generated by Django 5.1.1 on 2024-10-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
