# Generated by Django 5.1.1 on 2024-10-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processing', '0003_processingbatch_uploadedpdf_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='pdf_processing.processingbatch'),
        ),
    ]
